### ISSUE TITLE
Main Issue: Full implementation of 'Experiment' requirements

### ISSUE THREAD

**Issue by JiaYiChe** [CMPUT301W21T34/TrialRun#1]
### All user story functionality completed

- [ ] AS AN OWNER, publish an experiment with a description, region, and minimum number of trials #2 
- [ ] AS AN OWNER, unpublish an experiment #3
- [ ] AS AN OWNER, end an experiment - this leaves results available+public, but new results cannot be added. #4
- [ ] AS BOTH, be able to subscribe to an experiment to participate in it
- [ ] AS AN EXPERIMENTER, be able to execute trials for an experiment and upload them to the experiment.
- [ ] AS AN OWNER, be able to ignore certain experiment results
- [ ] AS BOTH, be able to observe statistics (quartiles, median, mean, stdev) about current trials
- [ ] AS BOTH, be able to see histograms of the results of trials
- [ ] AS BOTH, be able to see plots of the results of trials over time

**Comment by JiaYiChe** [comment]
risk level: low
